### ISSUE TITLE
I always get "Class does not have target metrics"

### ISSUE THREAD

**Issue by holger8080** [ZV3zrmCT/peloton_schwinn_metrics#1]
Great project, love the idea.
But sadly, I can't get it to work. I use safari on my MacBook, tried almost 10 classes, but always get the "Class does not have target metrics." message.

Is the bookmarklet still working in general? Have I just tried the 10 classes that don't support it, or am I doing something wrong?

**Comment by ZV3zrmCT** [comment]
The bookmarklet works in any cycling class that's about a day or more old. Peloton doesn't expose metrics for non-cycling classes. What's the URL of a class it's failing on?

**Comment by holger8080** [comment]
I tried 10 different classes, some a year old, some 1 or 3 days old. All cycling classes, I skipped the warmup and tried 5 different times - none worked.
E.g. "30 min Advanced Beginner Ride by LEANNE HAINSBY" from Fr. 11.10.19 at 10:25

I tested it in Safari on my MacBook and double-checked to have the newest bookmarklet installed.

**Comment by holger8080** [comment]
Tried it on my iPad with Safari last night. Did't work either, I also got the error message "Class does not have target metrics" on every course I tried (cycling, a few days old).

**Comment by ZV3zrmCT** [comment]
After invoking the bookmarklet, it sends a request to the Peloton API to pull the metrics. For example, in the metrics URL below, you should see a large list of metrics near the end of the file (look for "resistance_range"). If metrics are not there, Peloton is blocking your account from the metrics.

Metrics:
https://api.onepeloton.com/api/ride/cad1fe71c33341e6b78528fdbd1cd4bc/details?stream_source=multichannel

Class:
https://members.onepeloton.com/classes/player/cad1fe71c33341e6b78528fdbd1cd4bc

If you you see the metrics in the first link, trying running the bookmarklet in a class with Safari's Developer Tools open. On the Network tab, search for "details". Are any of those requests reporting errors?

**Comment by ZV3zrmCT** [comment]
Closing. Reopen if unresolved.
