### ISSUE TITLE
Tread metrics

### ISSUE THREAD

**Issue by blautob** [ZV3zrmCT/peloton_schwinn_metrics#4]
Hi is it possible to adapt the script for tread metrics?
They look a little different

> `"instructor_cues": [], "target_class_metrics": {}, "target_metrics_data": {"target_metrics": [{"offsets": {"start": 60, "end": 86}, "segment_type": "running", "metrics": [{"name": "speed", "upper": 6.4, "lower": 3.2}, {"name": "incline", "upper": 1.0, "lower": 0.0}]}, {"offsets": {"start": 87, "end": 131}, "segment_type": "running", "metrics": [{"name": "speed", "upper": 11.3, "lower": 6.4}, {"name": "incline", "upper": 1.0, "lower": 0.0}]}, {"offsets": {"start": 132, "end": 186}, "segment_type": "running", "metrics": [{"name": "speed", "upper": 11.6, "lower": 6.6}, {"name": "incline", "upper": 1.0, "lower": 0.0}]}, {"offsets": {"start": 187, "end": 267}, "segment_type": "running", "metrics": [{"name": "speed", "upper": 11.9, "lower": 6.8}, {"name": "incline", "upper": 1.0, "lower": 0.0}]}, {"offsets": {"start": 268, "end": 313}, "segment_type": "running", "metrics": [{"name": "speed", "upper": 14.5, "lower": 9.7}, {"name": `

**Comment by ZV3zrmCT** [comment]
Didn’t know the finally added it for the tread! I’ll take a look.

**Comment by blautob** [comment]
thanks a lot! Looking forward to it.
I use the bookmarklet on the bike already couple times a week and i LOVE it!thanks for your work...

**Comment by ZV3zrmCT** [comment]
Made some not glamorous edits, but the bookmarklets now show the tread target metrics. Add the latest from https://zv3zrmct.github.io/peloton_schwinn_metrics/

**Comment by blautob** [comment]
Works like a charm
