### ISSUE TITLE
Row metrics

### ISSUE THREAD

**Issue by blautob** [ZV3zrmCT/peloton_schwinn_metrics#5]
Hey there

after using the thread metrics i just found out today that they now also publish row classes and metrics.
If you could add those as well the package would be complete and fantastic :-)

`arget_metrics_data": {"target_metrics": [{"offsets": {"start": 60, "end": 62}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 63, "end": 133}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 134, "end": 185}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 24.0, "lower": 20.0}, {"name": "pace_intensity", "upper": 1.0, "lower": 1.0}]}, {"offsets": {"start": 186, "end": 215}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 216, "end": 246}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 24.0, "lower": 20.0}, {"name": "pace_intensity", "upper": 1.0, "lower": 1.0}]}, {"offsets": {"start": 247, "end": 266}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 26.0, "lower": 22.0}, {"name": "pace_intensity", "upper": 2.0, "lower": 2.0}]}, {"offsets": {"start": 267, "end": 289}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 290, "end": 319}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 26.0, "lower": 22.0}, {"name": "pace_intensity", "upper": 2.0, "lower": 2.0}]}, {"offsets": {"start": 320, "end": 435}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 436, "end": 462}, "`

**Comment by ZV3zrmCT** [comment]
thanks! was away, will take a look at adding this week.

**Comment by ZV3zrmCT** [comment]
Made updates -- try saving the latest bookmarklet from https://zv3zrmct.github.io/peloton_schwinn_metrics/ and give it a try for row metrics.

**Comment by blautob** [comment]
works great! thanks!
